/******************************************************************************
 *
 * Module: Ultrasonic Sensor
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic sensor driver.
 *
 * Author: Youssef Hassan
 *
 *******************************************************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <avr/io.h>
#include <util/delay.h>
#include <math.h>

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

static volatile uint16 g_echoStartTime = 0;
static volatile uint16 g_echoEndTime = 0;
static volatile uint8 g_edgeFlag = 0;

/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/

/*
 * Description:
 * Initializes the ultrasonic sensor by setting up the ICU driver,
 * configuring the trigger pin as output and echo pin as input.
 */
void Ultrasonic_init(void)
{
    /* Initialize the ICU driver with the required clock (F_CPU/8) and edge detection (rising) */
    ICU_ConfigType icuConfig = { F_CPU_8, RAISING };
    ICU_init(&icuConfig);

    /* Set ICU callback function to process echo pulse duration */
    ICU_setCallBack(Ultrasonic_edgeProcessing);

    /* Set the trigger pin direction to output */
    GPIO_setupPinDirection(ULTRASONIC_TRIG_PORT_ID, ULTRASONIC_TRIG_PIN_ID, PIN_OUTPUT);

    /* Set the echo pin direction to input (automatically set by ICU on PD6) */
    GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID, ULTRASONIC_ECHO_PIN_ID, PIN_INPUT);
}

/*
 * Description:
 * Sends a trigger pulse to the ultrasonic sensor.
 */
void Ultrasonic_Trigger(void)
{
    /* Send a 10us high pulse to the trigger pin to start measurement */
    GPIO_writePin(ULTRASONIC_TRIG_PORT_ID, ULTRASONIC_TRIG_PIN_ID, LOGIC_HIGH);
    _delay_us(10);
    GPIO_writePin(ULTRASONIC_TRIG_PORT_ID, ULTRASONIC_TRIG_PIN_ID, LOGIC_LOW);
}

/*
 * Description:
 * Initiates the measurement process by sending a trigger pulse and reading
 * the distance via the ICU driver.
 * Returns the measured distance in centimeters.
 */
uint16 Ultrasonic_readDistance(void)
{
    /* Send trigger pulse to start measurement */
    Ultrasonic_Trigger();

    /* Wait for both edges (rising and falling) to be detected and processed */
    while(g_edgeFlag != 2) {}

    /* Calculate the duration of the high pulse (time it took for the echo to return) */
    uint16 pulseDuration = g_echoEndTime - g_echoStartTime;

    /* Calculate the distance in centimeters (using speed of sound = 0.0343 cm/us) */
    uint16 distance = ceil((pulseDuration / 117.6));

    /* Reset the edgeFlag for the next measurement */
    g_edgeFlag = 0;

    ICU_clearTimerValue();

    return distance;
}

/*
 * Description:
 * This is the callback function that is called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
    if(g_edgeFlag == 0)
    {
        /* First edge detected (rising edge), record the start time */
        g_echoStartTime = ICU_getInputCaptureValue();
        ICU_setEdgeDetectionType(FALLING);  // Switch to falling edge
        g_edgeFlag = 1;
    }
    else if(g_edgeFlag == 1)
    {
        /* Second edge detected (falling edge), record the end time */
        g_echoEndTime = ICU_getInputCaptureValue();
        ICU_setEdgeDetectionType(RAISING);  // Switch back to rising edge
        g_edgeFlag = 2;  // Measurement complete
    }
}
